project:
  type: website
output-dir: docs

website:
  title: "Positive Hack Days 12"
  navbar:
    left:
      - href: index.qmd
        text: "Основная информация"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

