name: Pr_8

on:
  push:
    branches: 
     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      pages: write     
      id-token: write 
   
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
